#!/usr/bin/env bash
# Generate config/global-settings.json (Claude) and config/grok-config.toml (Grok)
# from marketplace.json so both harnesses reference this repo.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

python3 <<'PY'
import json
from pathlib import Path

root = Path(".").resolve()
mp = json.loads((root / ".claude-plugin" / "marketplace.json").read_text())
plugins = [p for p in mp.get("plugins", []) if p.get("name")]
names = sorted({p["name"] for p in plugins})

# --- Claude: ~/.claude/settings.json fragment ---
enabled = {f"{n}@rushy": True for n in names}
claude = {
    "$comment": (
        "Generated from marketplace.json. Apply with ./scripts/apply-global.sh. "
        "Claude plugins/skills resolve via *@rushy from this repo."
    ),
    "extraKnownMarketplaces": {
        "rushy": {
            "source": {
                "source": "github",
                "repo": "RUSHYOP/rushy-claude-plugins",
            }
        }
    },
    "enabledPlugins": dict(sorted(enabled.items())),
}
claude_path = root / "config" / "global-settings.json"
claude_path.parent.mkdir(parents=True, exist_ok=True)
claude_path.write_text(json.dumps(claude, indent=2) + "\n")
print(f"Wrote {claude_path} ({len(enabled)} plugins @rushy)")

# --- Grok: install sources + live paths ---
first_party_paths = []
skill_paths = []
install_sources = []  # for grok plugin install
enabled_names = []

for p in sorted(plugins, key=lambda x: x["name"]):
    name = p["name"]
    enabled_names.append(name)
    src = p["source"]
    meta = p.get("metadata") or {}
    if isinstance(src, str) and src.startswith("./plugins/"):
        abs_plugin = (root / src[2:]).resolve()
        first_party_paths.append(str(abs_plugin))
        skills = abs_plugin / "skills"
        if skills.is_dir():
            skill_paths.append(str(skills))
        install_sources.append({"name": name, "source": str(abs_plugin), "kind": "local"})
    elif isinstance(src, dict):
        url = src.get("url", "")
        path = (src.get("path") or "").strip("/")
        # RUSHYOP/mirror-foo#subdir
        if "github.com/RUSHYOP/" in url:
            repo = url.rstrip("/").split("github.com/")[-1].removesuffix(".git")
            source = f"{repo}#{path}" if path else repo
        elif url.startswith("https://github.com/"):
            repo = url.removesuffix(".git").split("github.com/")[-1]
            source = f"{repo}#{path}" if path else repo
        else:
            source = url if not path else f"{url}#{path}"
        install_sources.append({"name": name, "source": source, "kind": "git"})

# Install manifest for apply-global
install_path = root / "config" / "grok-install.json"
install_path.write_text(
    json.dumps(
        {
            "$comment": "Install specs for `grok plugin install` — generated by generate-global-config.sh",
            "first_party_plugin_paths": first_party_paths,
            "skill_paths": skill_paths,
            "enabled": enabled_names,
            "install": install_sources,
        },
        indent=2,
    )
    + "\n"
)
print(f"Wrote {install_path} ({len(install_sources)} install targets)")

# TOML fragment for humans / merge
def toml_str_list(key: str, items: list[str], indent: str = "") -> str:
    if not items:
        return f"{indent}{key} = []\n"
    lines = [f"{indent}{key} = ["]
    for it in items:
        esc = it.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{indent}  "{esc}",')
    lines.append(f"{indent}]")
    return "\n".join(lines) + "\n"

toml_lines = [
    "# Generated from marketplace.json — applied by ./scripts/apply-global.sh",
    "# Grok: plugins + skills reference Agentic-setup / rushy-claude-plugins",
    "",
    "[[marketplace.sources]]",
    'name = "rushy"',
    f'path = "{root}"',
    "",
    "[[marketplace.sources]]",
    'name = "rushy-git"',
    'git = "https://github.com/RUSHYOP/rushy-claude-plugins.git"',
    "",
    "[skills]",
    toml_str_list("paths", skill_paths).rstrip(),
    "",
    "[plugins]",
    toml_str_list("paths", first_party_paths).rstrip(),
    toml_str_list("enabled", enabled_names).rstrip(),
    "",
]
grok_toml = root / "config" / "grok-config.toml"
grok_toml.write_text("\n".join(toml_lines) + "\n")
print(f"Wrote {grok_toml}")
print(f"  first-party plugin paths: {len(first_party_paths)}")
print(f"  skill paths: {len(skill_paths)}")
print(f"  enabled plugins: {len(enabled_names)}")
PY
